apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:942d8233367fed8695094cf9d8eaf72c0b6706b3
        ports:
        - containerPort: 80
