apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 396606070456.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:a2c735c25e1217e293ba73b282acfa04f53a9b04
        ports:
        - containerPort: 80
