apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 065967698410.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:74a4ef42b9a248147aacd1ddee995a6abd673c59
        ports:
        - containerPort: 80
