apiVersion: v1
kind: Service
metadata:
  name: computers-service
  labels:
    app: computers
spec:
  type: ClusterIP
  selector:
    app: computers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
