apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/google-store-phones:d4ac6a48ce337cdf8fd3d1f6a32e0e9bc4fed3da
        ports:
        - containerPort: 80
