apiVersion: v1
kind: Service
metadata:
  name: phones-frontend-service
  labels:
    app: phones-frontend
spec:
  type: ClusterIP       # ðŸ‘ˆ Internal access only
  selector:
    app: phones-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
